from functools import wraps

import jwt as pyjwt
from flask import request, g

from app.extensions import db
from app.models.user import User
from app.utils.errors import AuthenticationError
from app.utils.jwt_utils import decode_token


def jwt_required(func=None, *, role=None, roles=None):
    """Require a valid access token, optionally with a required role.

    Usage::

        @jwt_required                       # any authenticated user
        @jwt_required(role='admin')         # admin only
        @jwt_required(roles=('admin', 'editor'))  # admin or editor

    - Missing / invalid / expired token → 401 ``AUTH_ERROR``.
    - Valid token but wrong role            → 403 ``AUTH_ERROR``.
    - Always loads the User row from the database; the JWT role claim is
      never trusted as the authorization source.
    """
    _allowed = None
    if roles is not None:
        _allowed = frozenset(roles)
    elif role is not None:
        _allowed = frozenset({role})

    def decorator(f):
        @wraps(f)
        def wrapper(*args, **kwargs):
            header = request.headers.get('Authorization', '')
            if not header.startswith('Bearer '):
                raise AuthenticationError('缺少认证令牌')

            token = header[7:]

            try:
                payload = decode_token(token, expected_type='access')
            except pyjwt.ExpiredSignatureError:
                raise AuthenticationError('认证令牌已过期')
            except pyjwt.InvalidTokenError:
                raise AuthenticationError('无效的认证令牌')

            # Tokens generated by this service use a canonical positive base-10
            # string subject. Reject booleans, floats, signs and leading zeros.
            raw_sub = payload.get('sub')
            if (
                not isinstance(raw_sub, str)
                or not raw_sub.isascii()
                or not raw_sub.isdecimal()
                or raw_sub.startswith('0')
                or len(raw_sub) > 19
            ):
                raise AuthenticationError('无效的认证令牌')

            user_id = int(raw_sub)
            if user_id <= 0 or user_id > 9_223_372_036_854_775_807:
                raise AuthenticationError('无效的认证令牌')

            user = db.session.get(User, user_id)
            if not user:
                raise AuthenticationError('用户不存在')

            if _allowed is not None and user.role not in _allowed:
                raise AuthenticationError('权限不足', http_status=403)

            g.current_user = user
            return f(*args, **kwargs)

        return wrapper

    if func is not None:
        return decorator(func)
    return decorator
